config/routes.rb
Rails.application.routes.draw do
   root "posts#index"
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  resources :users 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :posts do
      resources :comments
      resources :likes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true
class Post < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :user
  # after_save :set_user
  has_one_attached :video
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :likes
  enum post_type: %i[image video]
  validate :acceptable_image

  def acceptable_image
    return unless image.attached?
  end

end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord # rubocop:disable Style/Documentation
  has_secure_password
  has_many :posts
  # has_many :comments, through: :posts
  has_many :likes, through: :posts
  enum role: %i[user admin]
end

app/controllers/application_controller.rb
# rubocop:disable Layout/CommentIndentation
class ApplicationController < ActionController::Base
  helper_method :current_user
  include SessionsHelper

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:notice] = "Please log in."
      redirect_to login_url
    end
  end
#     private
  
#     # Finds the User with the ID stored in the session with the key
#     # :current_user_id This is a common way to handle user login in
#     # a Rails application; logging in sets the session value and
#     # logging out removes it.
#     def current_user
#       @_current_user ||= session[:current_user_id] &&
#         User.find_by(id: session[:current_user_id])
#     end
# end
#   def current_user
#     @current_user ||= User.find(session[:user_id]) if session[:user_id]
#   end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true
class CommentsController < ApplicationController # rubocop:disable Style/Documentation
  before_action :logged_in_user
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find_by_id(params[:post_id])
    # @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comments_params.merge(user_id: current_user.id))
    redirect_to post_path(@post)
  end
  # @comment = current_user.comments.create(comment_params)
  # redirect_to post_path(@comment.post)
  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comments_params)
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comments_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find_by_id(params[:post_id])
    @like = @post.likes.create(likes_params.merge(user_id: current_user.id))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(params[:id])
    @like.destroy
    redirect_to post_path(@post)
  end

  private  
  def likes_params
    params.require(:like).permit(:user)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController # rubocop:disable Style/Documentation
  before_action :logged_in_user
  def index
    @posts = Post.all
    return unless session[:user_id]
    @user = User.find_by(id: session[:user_id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(session[:user_id]) if session[:user_id]
    @post = Post.create(post_params)
    @post.user_id = @user.id
    @post.author_user = @user.name
    if @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @user = User.find(session[:user_id]) if session[:user_id]
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
    # redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:body, :title, :post_type, :image, :video, :user_id)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController # rubocop:disable Style/Documentation
  def new
    if logged_in?
      flash[:danger] = "you are logged in please log out."
      redirect_to root_path
    end
  end

  def create
    @user = User.find_by(email: user_params[:email])

    if @user&.authenticate(user_params[:password])

      session[:user_id] = @user.id
      flash[:notice] = 'Login successful'
      redirect_to '/posts'
    else
      flash[:notice] = 'Invalid email or Password'
      redirect_to '/login'
    end
  end

  def destroy
    # session.delete(:user_id)
    # session[:user_id] = nil
    # debugger
    # flash[:notice] = 'Logged Out'
    # redirect_to '/login'
    log_out
    redirect_to "/login"
  end

  private

  def user_params
    params.require(:user).permit(:password, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController # rubocop:disable Style/Documentation
  before_action :logged_in_user
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Signup successfull'
      redirect_to '/posts'
    else
      flash[:notice] = 'Please try again'
      redirect_to '/signup'
       render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.post, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<%= form_with model: [@post,@comment] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if current_user != nil%>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" ><%= link_to "Home", root_path, {class:"btn btn-primary"} %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="nav navbar-nav navbar-right">
        <a class="nav-link" ><%= link_to "logout",logout_path , {class:"btn btn-danger"} %></a>
        <a class="nav-link" ><%= link_to "New Post", new_post_path, {class:"btn btn-success"} %></a>
      </ul>
    </div>
  <%end%>
</nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%=form_with model: @post do |form| %>

<div>
  <%= form.label :body, class:"form-label" %><br>
  <%= form.text_field :body, class:"form-control" %>
</div> 

<div>
  <%= form.label :title, class:"form-label" %><br>
  <%= form.text_field :title, class:"form-control" %>
</div> 

<div>
  <%= form.label :post_type, class:"form-label"  %><br>
  <%= form.text_area :post_type, class:"form-control" %>
</div> 

<div>
  <%= form.label :image, class:"form-label"%>
  <%= form.file_field :image, class:"form-control"%>
</div>

<div>
  <%= form.label :video, class:"form-label"%>
  <%= form.file_field :video, class:"form-control"%>
</div>
<br>

<div class="col-12">
  <button type="submit" class="btn btn-primary">Submit</button>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>
<body style="background-color:powderblue;">
<%= render "posts/form" %>

app/views/posts/index.html.erb
<h1>Users Post</h1>
<html>
<head>
</head>
<body style="background-color:powderblue;">

<% if current_user = nil %>
<%= link_to "login",login_path %><br>
<% else current_user != nil %>

<h4 style="color:green;"> Welcome! <%= @current_user.name %> </h4>
<%end%>

<p style="background-color:tomato;">Our blog has <%= @posts.count %> posts</p>
<style>
table{
  width:100%;
  text-align:center
}
</style>
<table class="table table-bordered border-primary">
  <center><tr>
    <th style="background-color:#FFFFE0">Title</th>
    <th style="background-color:#FFFFE0">Name</th>
    <th style="background-color:#FFFFE0">description</th>
    <th style="background-color:#FFFFE0">type</th>
    <th style="background-color:#FFFFE0">Action</th>

  </tr></center>
  <tr>
  <% p=1 %>
  <% @posts.each do |post| %>

    <td>
      <%= link_to post.title, post %>
    </td>
  
    <td>
      <%= post.author_user %><br>
    </td>

    <td>
      <%= link_to post.body, post %><br>
    </td>

    <td>
      <%= post.post_type%><br>
    </td>

    <td>
      <pre>
        <% if @current_user.role == 'admin' || post.user_id == @current_user.id %>
        
        <%= link_to "Edit", edit_post_path(post),{class:"btn btn-primary"} %> || <%= link_to "Destroy", post_path(post),class:"btn btn-primary",  data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure for delete post?"
                      } %>
      </pre>
    </td>
<% end %>
</tr>

<% end %>

</table>
</body>
</html>

app/views/posts/new.html.erb
<h1>New Posts</h1>
<body style="background-color:powderblue;">
<%= render "posts/form" %>

app/views/posts/show.html.erb
<body style="background-color:powderblue;">
<h1><%= @post.body %></h1> 
<p><%= @post.title %></p>
<p><%= @post.post_type %></p>
<p><%= @post.user_id %></p>
<p><%= current_user.name %></p> 

<%= image_tag @post.image, height: 300, width:500 %> 

<% if @post.user_id == current_user.id %> 
<li><%= link_to "Edit", edit_post_path %></li> 
  <li>
    <%= link_to "Destroy", post_path(@post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure for delete post?"
                  } %>
                  </li>
 <% end %>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

<% if comment.user_id == current_user.id %> 
  <li><%= link_to "Edit", edit_post_comment_path(@post, comment) %></li>
   <%= link_to "Destroy Comment", post_comment_path(post_id:comment.post_id, id:comment.id), method: "delete" , data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
<% end %>
<% end %>

<h2>Add a comment:</h2>
<%= form_with model: [@post, @post.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
     <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
    <% @user.errors.full_messages_for(:age).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>
    <div>
    <%= form.label :password %><br>
    <%= form.text_area :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>
    <div>
    <%= form.label :email%><br>
    <%= form.text_area :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>
<%
=begin%>
 <ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.user_name,user %>
      <%= user.user_age%>
      <%=user.email%>
    </li>
  <% end %>
</ul> 
<%
=end%>
 <%= link_to "New User", new_user_path %>

 <h1> Hello and Welcome <h1> 
<% if current_user %>
  <%= link_to 'Logout', '/logout', :data => { :confirm => 'Are you sure?' }%>
<% else %>
  <%= link_to 'Signup', '/signup' %>
  <%= link_to 'Login', '/login'%>
<% end %>

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %> 

app/views/users/new.html.erb
<h1>New Users</h1>

<%= render "form", user: @user%>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= @user.age %></p>
<p><%=@user.email %></p>
<p><%=@user.posts %></p>
<ul>
  <li><%= link_to "Edit", edit_user_path(@user) %></li>
  <li><%= link_to "Destroy", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure for delete?"
                  } %></li>
</ul>